version: '3.7'

services:
  #API
  leaderboard:
    image: haithanh079/go-leaderboard:latest
#    build: .
    ports:
      - 8000:8000
  #REDIS
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    command: 
      - "--requirepass"
      - "tJNZfX44zeY57E"
    volumes:
      - ./redis/data:/data
  docs:
    image: swaggerapi/swagger-ui:latest
    ports:
      - 8032:8080
    environment:
      - SWAGGER_JSON=/home/docs/swagger.json
    volumes:
      - ~/:/home/docs
